# .github/deploy.yml
# ccascds
staging:
  # Auto deploy on master.
  auto_deploy_on: refs/heads/master
  # Wait for our ci pipeline to pass.
  required_contexts: ["ci"]
  environment: staging

prod:
  environment: prod
  production_environment: true
