# .github/workflows/ci.yml
name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
          # ansonsten werden freuhere commits nicht geholt .. die brauchts aber fuer den log
          fetch-depth: 0

    - name: git log since last tag
      id:   git_log
      run:  |
          content=$(git log --pretty=format:'- %h %s')
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=log::$content"

    - name: git commit message
      id: git_msg
      run: |
          content=$(git log -1 --pretty=format:'- %h %s')
          echo "::set-output name=msg::$content"

    - name: git branch
      id: git_branch
      run: |
          content=$(git branch | grep '^*' | tr -d '* ')
          echo "::set-output name=branch::$content"

    - name: install, build, and test
      run: |
        echo 'ok'
    - name: create ticket
      uses: JasonEtco/create-an-issue@v2
      id: create-issue
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.git_branch.outputs.branch }}
          GITLOG: ${{ steps.git_log.outputs.log }}
          MESSAGE: ${{ steps.git_msg.outputs.msg }}
      with:
          filename: .github/ISSUE_TEMPLATE.md
