name: 'Build'

on: [push]

jobs:
  build:

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@master'
    - name: 'Test'
      run: |
          echo "ok"
          date > datum.txt
    - name: archive artifact
      uses: actions/upload-artifact@v2
      with:
          name: etc
          retention-days: 1
          path: |
              README.md 
              datum.txt
